### ISSUE TITLE
Cannot use Handlebars partials

### ISSUE THREAD

**Issue by jamesarosen** [thomasboyt/broccoli-baked-handlebars#1]
I'd love to be able to do

``` hbs
{{!-- html/index.hbs --}}
{{> header}}
{{> main}}
{{> footer}}
```

but I get an exception:

```
Built with error:
File: index.hbs
Error
    at Object.<anonymous> (/Users/me/project/style/node_modules/broccoli-baked-handlebars/node_modules/handlebars/dist/cjs/handlebars/exception.js:26:23)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/me/project/node_modules/broccoli-baked-handlebars/node_modules/handlebars/dist/cjs/handlebars/base.js:3:17)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```

Part of the problem, I suspect, is that `broccoli-baked-handlebars` doesn't know about the rest of the tree since its first argument is just a tree containing the one main `index.hbs` file.

**Comment by jamesarosen** [comment]
For those who find this page because they have the same request, try [broccoli-render-handlebars](https://www.npmjs.com/package/broccoli-render-handlebars).
